### ISSUE TITLE
bug : Unlimited looting

### ISSUE THREAD

**Issue by PolSpock** [Xenikay/SimpleLootSystem#4]
https://github.com/Xenikay/SimpleLootSystem/blob/a49dfc0aaf1742483e8c1dfa3879428e7a86c797/lua/entities/looting_storage_base/init.lua#L121

**Bug found :**
Unlimited looting by pressing the 'use' key even if the item is already looted (in theory) .

**How to reproduce :**
Use for the first time the box : client side message appear and disappear correctly.
Use for the second time the box : the client side message "press 'touch' to loot" isn't displayed but i can still loot the box (just wait and imagine the progress bar)

**Fix suggestion :**
Remove the line :
self.NextSearch = CurTime()

**Comment by F1restar4** [comment]
You're right!
Must have missed that.
